"use client";
import { useEffect, useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"https://real-money-games-production.up.railway.app";
type D={id:string;amountPaise:string;utr:string;proofUrl:string|null;status:string;rejectionReason:string|null;createdAt:string;phoneNumber:string};
type W={id:string;amountPaise:string;upiId:string;status:string;rejectionReason:string|null;createdAt:string;phoneNumber:string;name:string};
type S={upiId:string;qrImageUrl:string;instructions:string};
const money=(p:string)=>`₹${(Number(p)/100).toFixed(2)}`;const defaultInstructions="Pay using the UPI ID or scan the QR code. Submit the UTR after payment.";
export default function AdminPage(){
 const[key,setKey]=useState("");const[ok,setOk]=useState(false);const[dash,setDash]=useState<any>(null);const[ds,setDs]=useState<D[]>([]);const[ws,setWs]=useState<W[]>([]);const[tab,setTab]=useState<"deposits"|"withdrawals">("deposits");const[status,setStatus]=useState("PENDING");const[settings,setSettings]=useState<S>({upiId:"",qrImageUrl:"",instructions:defaultInstructions});const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");
 async function api(path:string,options:RequestInit={}){const headers:Record<string,string>={"x-admin-key":key};if(options.body)headers["Content-Type"]="application/json";const r=await fetch(`${API}${path}`,{...options,headers:{...headers,...(options.headers||{})}});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.message||`Request failed (${r.status})`);return data;}
 async function load(){if(!key.trim()){setMsg("Enter the admin API key first.");return;}setBusy(true);setMsg("");try{const [a,b,c,d]=await Promise.all([api("/admin/dashboard"),api(`/admin/deposits?status=${tab==="deposits"?status:"PENDING"}`),api(`/admin/withdrawals?status=${tab==="withdrawals"?status:"PENDING"}`),api("/payment-settings")]);setDash(a);setDs(b);setWs(c);setSettings({upiId:c?.upiId||"",qrImageUrl:c?.qrImageUrl||"",instructions:c?.instructions||defaultInstructions});setOk(true);}catch(e){setOk(false);setMsg(e instanceof Error?e.message:"Unable to connect");}finally{setBusy(false);}}
 useEffect(()=>{if(ok)void load();},[tab,status]);
 async function act(path:string,body?:object){setBusy(true);setMsg("");try{await api(path,{method:"POST",body:body?JSON.stringify(body):undefined});setMsg("Action completed successfully.");await load();}catch(e){setMsg(e instanceof Error?e.message:"Action failed");setBusy(false);}}
 async function reject(path:string){const reason=prompt("Reason for rejection:");if(reason?.trim())await act(path,{reason});}
 async function saveSettings(){setBusy(true);try{const d=await api("/payment-settings",{method:"PUT",body:JSON.stringify(settings)});setSettings(d);setMsg("Payment settings saved.");}catch(e){setMsg(e instanceof Error?e.message:"Unable to save");}finally{setBusy(false);}}
 const card:React.CSSProperties={border:"1px solid rgba(255,255,255,.1)",borderRadius:20,padding:20,background:"rgba(255,255,255,.035)"};const button:React.CSSProperties={padding:"10px 14px",borderRadius:10,border:"1px solid rgba(255,255,255,.12)",background:"transparent",color:"white",cursor:"pointer",fontWeight:700};const input:React.CSSProperties={width:"100%",padding:13,borderRadius:12,border:"1px solid rgba(255,255,255,.12)",background:"rgba(0,0,0,.25)",color:"white",outline:"none"};
 return <main style={{minHeight:"100vh",padding:28,background:"#07080b",color:"white"}}><div style={{maxWidth:1180,margin:"auto"}}><header style={{display:"flex",justifyContent:"space-between",borderBottom:"1px solid rgba(255,255,255,.1)",paddingBottom:20}}><div><div style={{fontSize:12,letterSpacing:3,opacity:.45}}>ROLLRUSH</div><h1 style={{margin:"6px 0"}}>Admin Dashboard</h1><div style={{fontSize:12,opacity:.4}}>Beta operations</div></div>{ok&&<button style={button} onClick={()=>{setOk(false);setKey("")}}>Sign out</button>}</header>
 {!ok?<section style={{...card,maxWidth:560,margin:"70px auto"}}><p style={{opacity:.4}}>SECURE OPERATIONS</p><h2>Admin access</h2><p style={{opacity:.5}}>Enter the ADMIN_API_KEY configured in Railway Beta.</p><input style={input} type="password" value={key} onChange={e=>setKey(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void load()} placeholder="Admin API key"/><button disabled={busy} style={{...button,width:"100%",marginTop:12,background:"white",color:"black"}} onClick={()=>void load()}>{busy?"Connecting...":"Open dashboard"}</button>{msg&&<p style={{color:"#fca5a5"}}>{msg}</p>}</section>:<>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:14,marginTop:25}}>{[["Pending deposits",dash?.pendingDeposits],["Pending withdrawals",dash?.pendingWithdrawals],["Total users",dash?.totalUsers],["Games today",dash?.gamesToday]].map(x=><div style={card} key={String(x[0])}><div style={{opacity:.4,fontSize:12}}>{x[0]}</div><div style={{fontSize:32,fontWeight:800,marginTop:8}}>{x[1]??"—"}</div></div>)}</section>
 <section style={{...card,marginTop:18}}><h2 style={{marginTop:0}}>Payment settings</h2><p style={{opacity:.45,fontSize:13}}>Shared with Beta users.</p><div style={{display:"grid",gap:12,maxWidth:760}}><label>UPI ID<input style={{...input,marginTop:6}} value={settings.upiId} onChange={e=>setSettings({...settings,upiId:e.target.value})}/></label><label>QR image URL<input style={{...input,marginTop:6}} value={settings.qrImageUrl} onChange={e=>setSettings({...settings,qrImageUrl:e.target.value})}/></label><label>Payment instructions<textarea style={{...input,marginTop:6}} rows={3} value={settings.instructions} onChange={e=>setSettings({...settings,instructions:e.target.value})}/></label><button disabled={busy} style={{...button,background:"white",color:"black",width:"fit-content"}} onClick={()=>void saveSettings()}>Save payment settings</button></div></section>
 <section style={{...card,marginTop:18}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div style={{display:"flex",gap:8}}><button style={{...button,background:tab==="deposits"?"white":"transparent",color:tab==="deposits"?"black":"white"}} onClick={()=>{setTab("deposits");setStatus("PENDING")}}>Deposits</button><button style={{...button,background:tab==="withdrawals"?"white":"transparent",color:tab==="withdrawals"?"black":"white"}} onClick={()=>{setTab("withdrawals");setStatus("PENDING")}}>Withdrawals</button></div><div style={{display:"flex",gap:8}}>{(tab==="deposits"?["PENDING","APPROVED","REJECTED"]:["PENDING","PAID","REJECTED"]).map(s=><button key={s} style={{...button,background:status===s?"white":"transparent",color:status===s?"black":"white"}} onClick={()=>setStatus(s)}>{s}</button>)}</div></div>{msg&&<p style={{padding:12,background:"rgba(250,204,21,.08)",color:"#fde68a",borderRadius:12}}>{msg}</p>}
 {tab==="deposits"?<div style={{display:"grid",gap:10,marginTop:15}}>{ds.length===0?<p style={{textAlign:"center",opacity:.4}}>No {status.toLowerCase()} deposits.</p>:ds.map(d=><div key={d.id} style={card}><b style={{fontSize:18}}>{money(d.amountPaise)}</b><div style={{opacity:.55,marginTop:5}}>{d.phoneNumber} · UTR <b>{d.utr}</b></div>{d.proofUrl&&<a href={d.proofUrl} target="_blank" rel="noreferrer">View payment proof →</a>}<div style={{marginTop:5,opacity:.35,fontSize:12}}>{new Date(d.createdAt).toLocaleString()}</div>{d.status==="PENDING"&&<div style={{display:"flex",gap:8,marginTop:12}}><button disabled={busy} style={{...button,background:"white",color:"black"}} onClick={()=>{if(confirm("Approve and credit this deposit?"))void act(`/admin/deposits/${d.id}/approve`)}}>Approve & credit</button><button disabled={busy} style={button} onClick={()=>void reject(`/admin/deposits/${d.id}/reject`)}>Reject</button></div>}{d.rejectionReason&&<div style={{color:"#fca5a5",marginTop:8}}>Reason: {d.rejectionReason}</div>}</div>)}</div>:<div style={{display:"grid",gap:10,marginTop:15}}>{ws.length===0?<p style={{textAlign:"center",opacity:.4}}>No {status.toLowerCase()} withdrawals.</p>:ws.map(w=><div key={w.id} style={card}><b style={{fontSize:18}}>{money(w.amountPaise)}</b><div style={{marginTop:5,opacity:.6}}>{w.name||"Player"} · {w.phoneNumber}</div><div style={{marginTop:5}}>UPI: <b>{w.upiId}</b></div><div style={{marginTop:5,opacity:.35,fontSize:12}}>{new Date(w.createdAt).toLocaleString()}</div>{w.status==="PENDING"&&<><div style={{marginTop:12,padding:12,borderRadius:12,background:"rgba(255,255,255,.04)",opacity:.65,fontSize:13}}>Manually pay this amount to the UPI ID above, then mark it as paid.</div><div style={{display:"flex",gap:8,marginTop:12}}><button disabled={busy} style={{...button,background:"white",color:"black"}} onClick={()=>{if(confirm("Confirm that payment was sent?"))void act(`/admin/withdrawals/${w.id}/approve`)}}>Mark as paid</button><button disabled={busy} style={button} onClick={()=>void reject(`/admin/withdrawals/${w.id}/reject`)}>Reject</button></div></>}{w.rejectionReason&&<div style={{color:"#fca5a5",marginTop:8}}>Reason: {w.rejectionReason}</div>}</div>)}</div>}
 </section></>}</div></main>;
}
