"use client";
import { useEffect, useState } from "react";

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "https://real-money-games-production.up.railway.app";
type Deposit={id:string;amountPaise:string;utr:string;proofUrl:string|null;status:string;rejectionReason:string|null;createdAt:string;phoneNumber:string};
type Dashboard={pendingDeposits:number;pendingWithdrawals:number;totalUsers:number;gamesToday:number};
type PaymentSettings={upiId:string;qrImageUrl:string;instructions:string};
const DEFAULT_INSTRUCTIONS="Pay using the UPI ID or scan the QR code. Submit the UTR after payment.";
const money=(p:string)=>`₹${(Number(p)/100).toFixed(2)}`;
const normalize=(v:any):PaymentSettings=>({upiId:typeof v?.upiId==="string"?v.upiId:"",qrImageUrl:typeof v?.qrImageUrl==="string"?v.qrImageUrl:"",instructions:typeof v?.instructions==="string"&&v.instructions.trim()?v.instructions:DEFAULT_INSTRUCTIONS});

export default function AdminPage(){
 const[key,setKey]=useState("");const[auth,setAuth]=useState(false);const[dash,setDash]=useState<Dashboard|null>(null);const[deposits,setDeposits]=useState<Deposit[]>([]);const[status,setStatus]=useState("PENDING");const[loading,setLoading]=useState(false);const[msg,setMsg]=useState("");const[settings,setSettings]=useState<PaymentSettings>({upiId:"",qrImageUrl:"",instructions:DEFAULT_INSTRUCTIONS});
 async function api(path:string,opt:RequestInit={}){const h:Record<string,string>={"x-admin-key":key};if(opt.body)h["Content-Type"]="application/json";let r:Response;try{r=await fetch(`${API_BASE_URL}${path}`,{...opt,headers:{...h,...(opt.headers||{})}})}catch{throw new Error(`Cannot connect to API at ${API_BASE_URL}`)}const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||`Request failed (${r.status})`);return d}
 async function load(s=status){if(!key.trim()){setMsg("Enter the admin API key first.");return}setLoading(true);setMsg("");try{const[a,b,c]=await Promise.all([api("/admin/dashboard"),api(`/admin/deposits?status=${s}`),api("/payment-settings")]);setDash(a);setDeposits(b);setSettings(normalize(c));setAuth(true)}catch(e){setAuth(false);setMsg(e instanceof Error?e.message:"Unable to connect")}finally{setLoading(false)}}
 useEffect(()=>{if(auth)void load(status)},[status]);
 async function save(){setLoading(true);setMsg("");try{const d=await api("/payment-settings",{method:"PUT",body:JSON.stringify(settings)});setSettings(normalize(d));setMsg("Payment settings saved successfully. Beta users will see the same settings.")}catch(e){setMsg(e instanceof Error?e.message:"Unable to save settings")}finally{setLoading(false)}}
 async function approve(id:string){if(!confirm("Approve this deposit and credit the wallet?"))return;setLoading(true);try{await api(`/admin/deposits/${id}/approve`,{method:"POST"});setMsg("Deposit approved and wallet credited.");await load(status)}catch(e){setMsg(e instanceof Error?e.message:"Approval failed");setLoading(false)}}
 async function reject(id:string){const reason=prompt("Reason for rejection:");if(!reason?.trim())return;setLoading(true);try{await api(`/admin/deposits/${id}/reject`,{method:"POST",body:JSON.stringify({reason})});setMsg("Deposit rejected.");await load(status)}catch(e){setMsg(e instanceof Error?e.message:"Rejection failed");setLoading(false)}}
 const card:React.CSSProperties={border:"1px solid rgba(255,255,255,.1)",borderRadius:20,padding:20,background:"rgba(255,255,255,.035)"};const input:React.CSSProperties={width:"100%",padding:13,borderRadius:12,border:"1px solid rgba(255,255,255,.12)",background:"rgba(0,0,0,.25)",color:"white",outline:"none"};const btn:React.CSSProperties={padding:"10px 14px",borderRadius:10,border:"1px solid rgba(255,255,255,.12)",background:"transparent",color:"white",cursor:"pointer",fontWeight:700};
 return <main style={{minHeight:"100vh",padding:"28px 18px"}}><div style={{maxWidth:1180,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid rgba(255,255,255,.1)",paddingBottom:20}}><div><div style={{fontSize:12,letterSpacing:3,opacity:.45}}>ROLLRUSH</div><h1 style={{margin:"6px 0",fontSize:30}}>Admin Dashboard</h1><div style={{fontSize:12,opacity:.4}}>API: {API_BASE_URL}</div></div>{auth&&<button onClick={()=>{setAuth(false);setKey("")}} style={btn}>Sign out</button>}</header>
 {!auth?<section style={{maxWidth:560,margin:"70px auto",...card}}><p style={{fontSize:12,letterSpacing:2,opacity:.4}}>SECURE OPERATIONS</p><h2>Admin access</h2><p style={{opacity:.5}}>Enter the ADMIN_API_KEY configured in Railway Beta.</p><input value={key} onChange={e=>setKey(e.target.value)} type="password" placeholder="Admin API key" onKeyDown={e=>{if(e.key==="Enter")void load()}} style={input}/><button disabled={loading} onClick={()=>void load()} style={{...btn,width:"100%",marginTop:12,background:"white",color:"black"}}>{loading?"Connecting...":"Open dashboard"}</button>{msg&&<p style={{marginTop:14,color:"#fca5a5"}}>{msg}</p>}</section>:<>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:14,marginTop:26}}>{[["Pending deposits",dash?.pendingDeposits],["Pending withdrawals",dash?.pendingWithdrawals],["Total users",dash?.totalUsers],["Games today",dash?.gamesToday]].map(([l,v])=><div key={String(l)} style={card}><div style={{fontSize:12,opacity:.4}}>{l}</div><div style={{fontSize:32,fontWeight:800,marginTop:8}}>{v??"—"}</div></div>)}</section>
 <section style={{marginTop:18,...card}}><h2 style={{marginTop:0}}>Payment settings</h2><p style={{opacity:.45,fontSize:13}}>These settings are saved to the Beta Railway database used by RollRush users.</p><div style={{display:"grid",gap:14,maxWidth:760}}><label>UPI ID<input value={settings.upiId} onChange={e=>setSettings({...settings,upiId:e.target.value})} placeholder="yourname@upi" style={{...input,marginTop:7}}/></label><label>QR image URL (optional)<input value={settings.qrImageUrl} onChange={e=>setSettings({...settings,qrImageUrl:e.target.value})} placeholder="https://.../qr.png" style={{...input,marginTop:7}}/></label><label>Payment instructions<textarea value={settings.instructions} onChange={e=>setSettings({...settings,instructions:e.target.value})} rows={3} style={{...input,marginTop:7,resize:"vertical"}}/></label><button disabled={loading} onClick={()=>void save()} style={{...btn,width:"fit-content",background:"white",color:"black"}}>{loading?"Saving...":"Save payment settings"}</button></div></section>
 <section style={{marginTop:18,...card}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:0}}>Deposit requests</h2></div><div style={{display:"flex",gap:8}}>{["PENDING","APPROVED","REJECTED"].map(s=><button key={s} onClick={()=>setStatus(s)} style={{...btn,background:status===s?"white":"transparent",color:status===s?"black":"white"}}>{s}</button>)}</div></div>{msg&&<div style={{marginTop:16,padding:12,borderRadius:12,background:"rgba(250,204,21,.08)",color:"#fde68a"}}>{msg}</div>}<div style={{marginTop:18,display:"grid",gap:10}}>{deposits.length===0?<div style={{padding:35,textAlign:"center",opacity:.4}}>No {status.toLowerCase()} deposits.</div>:deposits.map(d=><div key={d.id} style={{border:"1px solid rgba(255,255,255,.08)",borderRadius:18,padding:16}}><div style={{display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:18,fontWeight:800}}>{money(d.amountPaise)}</div><div style={{marginTop:5,fontSize:13,opacity:.55}}>{d.phoneNumber} · UTR <b>{d.utr}</b></div><div style={{marginTop:5,fontSize:12,opacity:.35}}>{new Date(d.createdAt).toLocaleString()}</div></div><span>{d.status}</span></div>{d.proofUrl&&<a href={d.proofUrl} target="_blank" rel="noreferrer">View payment proof →</a>}{d.status==="PENDING"&&<div style={{display:"flex",gap:9,marginTop:14}}><button disabled={loading} onClick={()=>void approve(d.id)} style={{...btn,background:"white",color:"black"}}>Approve & credit</button><button disabled={loading} onClick={()=>void reject(d.id)} style={btn}>Reject</button></div>}{d.rejectionReason&&<div style={{marginTop:12,color:"#fca5a5"}}>Reason: {d.rejectionReason}</div>}</div>)}</div></section>
 </>}</div></main>;
}